export enum JobSchedule {
  DAILY_AT_1_AM_UTC = "0 1 * * *",
  DAILY_AT_MIDNIGHT_UTC = "0 0 * * *",
  EVERY_10_MINUTES = "*/10 * * * *",
  EVERY_12_HOURS = "0 */12 * * *",
  EVERY_15_MINUTES = "*/15 * * * *",
  EVERY_30_MINUTES = "*/30 * * * *",
  EVERY_3_HOURS = "0 */3 * * *",
  EVERY_5_MINUTES = "*/5 * * * *",
  EVERY_6_HOURS = "0 */6 * * *",
  EVERY_MINUTE = "* * * * *",
  HOURLY = "0 * * * *",
  MONTHLY_AT_MIDNIGHT_UTC = "0 0 1 * *",
  WEEKLY_AT_MIDNIGHT_UTC = "0 0 * * 7",
}
